import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Creates and seeds Nigeria's administrative geography:
 *   • states  — 36 states + FCT (37 rows), with capital and geopolitical zone
 *   • lgas    — the 774 official Local Government Areas (the "districts"),
 *               each linked to its state, with the official INEC LGA code.
 *
 * Source of the LGA list: INEC (Independent National Electoral Commission),
 * 774 LGAs — the authoritative administrative division of Nigeria.
 * Seed is idempotent (ON CONFLICT DO NOTHING) so re-running is safe.
 */
export class CreateStatesAndLgas1788474966526 implements MigrationInterface {
  name = 'CreateStatesAndLgas1788474966526';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // ── states ────────────────────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE "states" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "deletedAt" TIMESTAMP,
        "updatedBy" character varying,
        "createdBy" character varying,
        "name" character varying NOT NULL,
        "code" character varying NOT NULL,
        "capital" character varying NOT NULL,
        "geopoliticalZone" character varying NOT NULL,
        "slug" character varying NOT NULL,
        CONSTRAINT "PK_states_id" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_states_name" UNIQUE ("name"),
        CONSTRAINT "UQ_states_code" UNIQUE ("code"),
        CONSTRAINT "UQ_states_slug" UNIQUE ("slug")
      )
    `);

    // ── lgas (Local Government Areas / districts) ──────────────────────────
    await queryRunner.query(`
      CREATE TABLE "lgas" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "deletedAt" TIMESTAMP,
        "updatedBy" character varying,
        "createdBy" character varying,
        "name" character varying NOT NULL,
        "slug" character varying NOT NULL,
        "inecCode" character varying,
        "stateId" uuid NOT NULL,
        CONSTRAINT "PK_lgas_id" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_lgas_state_name" UNIQUE ("stateId", "name")
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_lgas_stateId" ON "lgas" ("stateId")`);
    await queryRunner.query(`
      ALTER TABLE "lgas"
      ADD CONSTRAINT "FK_lgas_stateId"
      FOREIGN KEY ("stateId") REFERENCES "states"("id")
      ON DELETE CASCADE ON UPDATE NO ACTION
    `);

    // ── seed: states ───────────────────────────────────────────────────────
    await queryRunner.query(`
      INSERT INTO "states" ("name", "code", "capital", "geopoliticalZone", "slug")
      VALUES
        ('Abia', 'AB', 'Umuahia', 'South East', 'abia'),
        ('Adamawa', 'AD', 'Yola', 'North East', 'adamawa'),
        ('Akwa Ibom', 'AK', 'Uyo', 'South South', 'akwa-ibom'),
        ('Anambra', 'AN', 'Awka', 'South East', 'anambra'),
        ('Bauchi', 'BA', 'Bauchi', 'North East', 'bauchi'),
        ('Bayelsa', 'BY', 'Yenagoa', 'South South', 'bayelsa'),
        ('Benue', 'BE', 'Makurdi', 'North Central', 'benue'),
        ('Borno', 'BO', 'Maiduguri', 'North East', 'borno'),
        ('Cross River', 'CR', 'Calabar', 'South South', 'cross-river'),
        ('Delta', 'DE', 'Asaba', 'South South', 'delta'),
        ('Ebonyi', 'EB', 'Abakaliki', 'South East', 'ebonyi'),
        ('Edo', 'ED', 'Benin City', 'South South', 'edo'),
        ('Ekiti', 'EK', 'Ado-Ekiti', 'South West', 'ekiti'),
        ('Enugu', 'EN', 'Enugu', 'South East', 'enugu'),
        ('Gombe', 'GO', 'Gombe', 'North East', 'gombe'),
        ('Imo', 'IM', 'Owerri', 'South East', 'imo'),
        ('Jigawa', 'JI', 'Dutse', 'North West', 'jigawa'),
        ('Kaduna', 'KD', 'Kaduna', 'North West', 'kaduna'),
        ('Kano', 'KN', 'Kano', 'North West', 'kano'),
        ('Katsina', 'KT', 'Katsina', 'North West', 'katsina'),
        ('Kebbi', 'KE', 'Birnin Kebbi', 'North West', 'kebbi'),
        ('Kogi', 'KO', 'Lokoja', 'North Central', 'kogi'),
        ('Kwara', 'KW', 'Ilorin', 'North Central', 'kwara'),
        ('Lagos', 'LA', 'Ikeja', 'South West', 'lagos'),
        ('Nasarawa', 'NA', 'Lafia', 'North Central', 'nasarawa'),
        ('Niger', 'NI', 'Minna', 'North Central', 'niger'),
        ('Ogun', 'OG', 'Abeokuta', 'South West', 'ogun'),
        ('Ondo', 'ON', 'Akure', 'South West', 'ondo'),
        ('Osun', 'OS', 'Osogbo', 'South West', 'osun'),
        ('Oyo', 'OY', 'Ibadan', 'South West', 'oyo'),
        ('Plateau', 'PL', 'Jos', 'North Central', 'plateau'),
        ('Rivers', 'RI', 'Port Harcourt', 'South South', 'rivers'),
        ('Sokoto', 'SO', 'Sokoto', 'North West', 'sokoto'),
        ('Taraba', 'TA', 'Jalingo', 'North East', 'taraba'),
        ('Yobe', 'YO', 'Damaturu', 'North East', 'yobe'),
        ('Zamfara', 'ZA', 'Gusau', 'North West', 'zamfara'),
        ('Federal Capital Territory', 'FC', 'Abuja', 'North Central', 'federal-capital-territory')
      ON CONFLICT ("name") DO NOTHING
    `);

    // ── seed: lgas (stateId resolved by joining on state name) ─────────────
    await queryRunner.query(`
      INSERT INTO "lgas" ("name", "slug", "inecCode", "stateId")
      SELECT v.name, v.slug, v.inec_code, s.id
      FROM (VALUES
        ('Aba North', 'aba-north', '01', 'Abia'),
        ('Aba South', 'aba-south', '02', 'Abia'),
        ('Arochukwu', 'arochukwu', '03', 'Abia'),
        ('Bende', 'bende', '04', 'Abia'),
        ('Ikwuano', 'ikwuano', '05', 'Abia'),
        ('Isiala Ngwa North', 'isiala-ngwa-north', '06', 'Abia'),
        ('Isiala Ngwa South', 'isiala-ngwa-south', '07', 'Abia'),
        ('Isuikwuato', 'isuikwuato', '08', 'Abia'),
        ('Obingwa', 'obingwa', '09', 'Abia'),
        ('Ohafia', 'ohafia', '10', 'Abia'),
        ('Osisioma', 'osisioma', '11', 'Abia'),
        ('Ugwunagbo', 'ugwunagbo', '12', 'Abia'),
        ('Ukwa East', 'ukwa-east', '13', 'Abia'),
        ('Ukwa West', 'ukwa-west', '14', 'Abia'),
        ('Umuahia North', 'umuahia-north', '15', 'Abia'),
        ('Umuahia South', 'umuahia-south', '16', 'Abia'),
        ('Umu-Nneochi', 'umu-nneochi', '17', 'Abia'),
        ('Demsa', 'demsa', '01', 'Adamawa'),
        ('Fufore', 'fufore', '02', 'Adamawa'),
        ('Ganye', 'ganye', '03', 'Adamawa'),
        ('Girei', 'girei', '04', 'Adamawa'),
        ('Gombi', 'gombi', '05', 'Adamawa'),
        ('Guyuk', 'guyuk', '06', 'Adamawa'),
        ('Hong', 'hong', '07', 'Adamawa'),
        ('Jada', 'jada', '08', 'Adamawa'),
        ('Lamurde', 'lamurde', '09', 'Adamawa'),
        ('Madagali', 'madagali', '10', 'Adamawa'),
        ('Maiha', 'maiha', '11', 'Adamawa'),
        ('Mayo-Belwa', 'mayo-belwa', '12', 'Adamawa'),
        ('Michika', 'michika', '13', 'Adamawa'),
        ('Mubi North', 'mubi-north', '14', 'Adamawa'),
        ('Mubi South', 'mubi-south', '15', 'Adamawa'),
        ('Numan', 'numan', '16', 'Adamawa'),
        ('Shelleng', 'shelleng', '17', 'Adamawa'),
        ('Song', 'song', '18', 'Adamawa'),
        ('Toungo', 'toungo', '19', 'Adamawa'),
        ('Yola North', 'yola-north', '20', 'Adamawa'),
        ('Yola South', 'yola-south', '21', 'Adamawa'),
        ('Abak', 'abak', '01', 'Akwa Ibom'),
        ('Eastern Obolo', 'eastern-obolo', '02', 'Akwa Ibom'),
        ('Eket', 'eket', '03', 'Akwa Ibom'),
        ('Esit Eket (Uquo)', 'esit-eket-uquo', '04', 'Akwa Ibom'),
        ('Essien Udim', 'essien-udim', '05', 'Akwa Ibom'),
        ('Etim Ekpo', 'etim-ekpo', '06', 'Akwa Ibom'),
        ('Etinan', 'etinan', '07', 'Akwa Ibom'),
        ('Ibeno', 'ibeno', '08', 'Akwa Ibom'),
        ('Ibesikpo Asutan', 'ibesikpo-asutan', '09', 'Akwa Ibom'),
        ('Ibiono Ibom', 'ibiono-ibom', '10', 'Akwa Ibom'),
        ('Ika', 'ika', '11', 'Akwa Ibom'),
        ('Ikono', 'ikono', '12', 'Akwa Ibom'),
        ('Ikot Abasi', 'ikot-abasi', '13', 'Akwa Ibom'),
        ('Ikot Ekpene', 'ikot-ekpene', '14', 'Akwa Ibom'),
        ('Ini', 'ini', '15', 'Akwa Ibom'),
        ('Itu', 'itu', '16', 'Akwa Ibom'),
        ('Mbo', 'mbo', '17', 'Akwa Ibom'),
        ('Mkpat Enin', 'mkpat-enin', '18', 'Akwa Ibom'),
        ('Nsit Atai', 'nsit-atai', '19', 'Akwa Ibom'),
        ('Nsit Ibom', 'nsit-ibom', '20', 'Akwa Ibom'),
        ('Nsit Ubium', 'nsit-ubium', '21', 'Akwa Ibom'),
        ('Obot Akara', 'obot-akara', '22', 'Akwa Ibom'),
        ('Okobo', 'okobo', '23', 'Akwa Ibom'),
        ('Onna', 'onna', '24', 'Akwa Ibom'),
        ('Oron', 'oron', '25', 'Akwa Ibom'),
        ('Oruk Anam', 'oruk-anam', '26', 'Akwa Ibom'),
        ('Udung Uko', 'udung-uko', '27', 'Akwa Ibom'),
        ('Ukanafun', 'ukanafun', '28', 'Akwa Ibom'),
        ('Uruan', 'uruan', '29', 'Akwa Ibom'),
        ('Urue Offong/Oruko', 'urue-offong-oruko', '30', 'Akwa Ibom'),
        ('Uyo', 'uyo', '31', 'Akwa Ibom'),
        ('Aguata', 'aguata', '01', 'Anambra'),
        ('Ayamelum', 'ayamelum', '02', 'Anambra'),
        ('Anambra East', 'anambra-east', '03', 'Anambra'),
        ('Anambra West', 'anambra-west', '04', 'Anambra'),
        ('Anaocha', 'anaocha', '05', 'Anambra'),
        ('Awka North', 'awka-north', '06', 'Anambra'),
        ('Awka South', 'awka-south', '07', 'Anambra'),
        ('Dunukofia', 'dunukofia', '08', 'Anambra'),
        ('Ekwusigo', 'ekwusigo', '09', 'Anambra'),
        ('Idemili North', 'idemili-north', '10', 'Anambra'),
        ('Idemili-South', 'idemili-south', '11', 'Anambra'),
        ('Ihiala', 'ihiala', '12', 'Anambra'),
        ('Njikoka', 'njikoka', '13', 'Anambra'),
        ('Nnewi North', 'nnewi-north', '14', 'Anambra'),
        ('Nnewi South', 'nnewi-south', '15', 'Anambra'),
        ('Ogbaru', 'ogbaru', '16', 'Anambra'),
        ('Onitsha-North', 'onitsha-north', '17', 'Anambra'),
        ('Onitsha-South', 'onitsha-south', '18', 'Anambra'),
        ('Orumba North', 'orumba-north', '19', 'Anambra'),
        ('Orumba South', 'orumba-south', '20', 'Anambra'),
        ('Oyi', 'oyi', '21', 'Anambra'),
        ('Alkaleri', 'alkaleri', '01', 'Bauchi'),
        ('Bauchi', 'bauchi', '02', 'Bauchi'),
        ('Bogoro', 'bogoro', '03', 'Bauchi'),
        ('Dambam', 'dambam', '04', 'Bauchi'),
        ('Darazo', 'darazo', '05', 'Bauchi'),
        ('Dass', 'dass', '06', 'Bauchi'),
        ('Gamawa', 'gamawa', '07', 'Bauchi'),
        ('Ganjuwa', 'ganjuwa', '08', 'Bauchi'),
        ('Giade', 'giade', '09', 'Bauchi'),
        ('Itas/Gadau', 'itas-gadau', '10', 'Bauchi'),
        ('Jama''are', 'jamaare', '11', 'Bauchi'),
        ('Katagum', 'katagum', '12', 'Bauchi'),
        ('Kirfi', 'kirfi', '13', 'Bauchi'),
        ('Misau', 'misau', '14', 'Bauchi'),
        ('Ningi', 'ningi', '15', 'Bauchi'),
        ('Shira', 'shira', '16', 'Bauchi'),
        ('Tafawa Balewa', 'tafawa-balewa', '17', 'Bauchi'),
        ('Toro', 'toro', '18', 'Bauchi'),
        ('Warji', 'warji', '19', 'Bauchi'),
        ('Zaki', 'zaki', '20', 'Bauchi'),
        ('Brass', 'brass', '01', 'Bayelsa'),
        ('Ekeremor', 'ekeremor', '02', 'Bayelsa'),
        ('Kolokuma/Opokuma', 'kolokuma-opokuma', '03', 'Bayelsa'),
        ('Nembe', 'nembe', '04', 'Bayelsa'),
        ('Ogbia', 'ogbia', '05', 'Bayelsa'),
        ('Sagbama', 'sagbama', '06', 'Bayelsa'),
        ('Southern Ijaw', 'southern-ijaw', '07', 'Bayelsa'),
        ('Yenagoa', 'yenagoa', '08', 'Bayelsa'),
        ('Ado', 'ado', '01', 'Benue'),
        ('Agatu', 'agatu', '02', 'Benue'),
        ('Apa', 'apa', '03', 'Benue'),
        ('Buruku', 'buruku', '04', 'Benue'),
        ('Gboko', 'gboko', '05', 'Benue'),
        ('Guma', 'guma', '06', 'Benue'),
        ('Gwer East', 'gwer-east', '07', 'Benue'),
        ('Gwer West', 'gwer-west', '08', 'Benue'),
        ('Katsina-Ala', 'katsina-ala', '09', 'Benue'),
        ('Konshisha', 'konshisha', '10', 'Benue'),
        ('Kwande', 'kwande', '11', 'Benue'),
        ('Logo', 'logo', '12', 'Benue'),
        ('Makurdi', 'makurdi', '13', 'Benue'),
        ('Obi', 'obi', '14', 'Benue'),
        ('Ogbadibo', 'ogbadibo', '15', 'Benue'),
        ('Oju', 'oju', '16', 'Benue'),
        ('Ohimini', 'ohimini', '17', 'Benue'),
        ('Okpokwu', 'okpokwu', '18', 'Benue'),
        ('Otukpo', 'otukpo', '19', 'Benue'),
        ('Tarka', 'tarka', '20', 'Benue'),
        ('Ukum', 'ukum', '21', 'Benue'),
        ('Ushongo', 'ushongo', '22', 'Benue'),
        ('Vandeikya', 'vandeikya', '23', 'Benue'),
        ('Abadam', 'abadam', '01', 'Borno'),
        ('Askira/Uba', 'askira-uba', '02', 'Borno'),
        ('Bama', 'bama', '03', 'Borno'),
        ('Bayo', 'bayo', '04', 'Borno'),
        ('Biu', 'biu', '05', 'Borno'),
        ('Chibok', 'chibok', '06', 'Borno'),
        ('Damboa', 'damboa', '07', 'Borno'),
        ('Dikwa', 'dikwa', '08', 'Borno'),
        ('Gubio', 'gubio', '09', 'Borno'),
        ('Guzamala', 'guzamala', '10', 'Borno'),
        ('Gwoza', 'gwoza', '11', 'Borno'),
        ('Hawul', 'hawul', '12', 'Borno'),
        ('Jere', 'jere', '13', 'Borno'),
        ('Kaga', 'kaga', '14', 'Borno'),
        ('Kala Balge', 'kala-balge', '15', 'Borno'),
        ('Konduga', 'konduga', '16', 'Borno'),
        ('Kukawa', 'kukawa', '17', 'Borno'),
        ('Kwaya/Kusar', 'kwaya-kusar', '18', 'Borno'),
        ('Mafa', 'mafa', '19', 'Borno'),
        ('Magumeri', 'magumeri', '20', 'Borno'),
        ('Maiduguri', 'maiduguri', '21', 'Borno'),
        ('Marte', 'marte', '22', 'Borno'),
        ('Mobbar', 'mobbar', '23', 'Borno'),
        ('Monguno', 'monguno', '24', 'Borno'),
        ('Ngala', 'ngala', '25', 'Borno'),
        ('Nganzai', 'nganzai', '26', 'Borno'),
        ('Shani', 'shani', '27', 'Borno'),
        ('Abi', 'abi', '01', 'Cross River'),
        ('Akamkpa', 'akamkpa', '02', 'Cross River'),
        ('Akpabuyo', 'akpabuyo', '03', 'Cross River'),
        ('Bakassi', 'bakassi', '04', 'Cross River'),
        ('Bekwarra', 'bekwarra', '05', 'Cross River'),
        ('Biase', 'biase', '06', 'Cross River'),
        ('Boki', 'boki', '07', 'Cross River'),
        ('Calabar Municipality', 'calabar-municipality', '08', 'Cross River'),
        ('Calabar South', 'calabar-south', '09', 'Cross River'),
        ('Etung', 'etung', '10', 'Cross River'),
        ('Ikom', 'ikom', '11', 'Cross River'),
        ('Obanliku', 'obanliku', '12', 'Cross River'),
        ('Obubra', 'obubra', '13', 'Cross River'),
        ('Obudu', 'obudu', '14', 'Cross River'),
        ('Odukpani', 'odukpani', '15', 'Cross River'),
        ('Ogoja', 'ogoja', '16', 'Cross River'),
        ('Yakurr', 'yakurr', '17', 'Cross River'),
        ('Yala', 'yala', '18', 'Cross River'),
        ('Aniocha North', 'aniocha-north', '01', 'Delta'),
        ('Aniocha-South', 'aniocha-south', '02', 'Delta'),
        ('Bomadi', 'bomadi', '03', 'Delta'),
        ('Burutu', 'burutu', '04', 'Delta'),
        ('Ethiope East', 'ethiope-east', '05', 'Delta'),
        ('Ethiope West', 'ethiope-west', '06', 'Delta'),
        ('Ika North-East', 'ika-north-east', '07', 'Delta'),
        ('Ika-South', 'ika-south', '08', 'Delta'),
        ('Isoko North', 'isoko-north', '09', 'Delta'),
        ('Isoko South', 'isoko-south', '10', 'Delta'),
        ('Ndokwa East', 'ndokwa-east', '11', 'Delta'),
        ('Ndokwa West', 'ndokwa-west', '12', 'Delta'),
        ('Okpe', 'okpe', '13', 'Delta'),
        ('Oshimili-North', 'oshimili-north', '14', 'Delta'),
        ('Oshimili-South', 'oshimili-south', '15', 'Delta'),
        ('Patani', 'patani', '16', 'Delta'),
        ('Sapele', 'sapele', '17', 'Delta'),
        ('Udu', 'udu', '18', 'Delta'),
        ('Ughelli North', 'ughelli-north', '19', 'Delta'),
        ('Ughelli South', 'ughelli-south', '20', 'Delta'),
        ('Ukwuani', 'ukwuani', '21', 'Delta'),
        ('Uvwie', 'uvwie', '22', 'Delta'),
        ('Warri North', 'warri-north', '23', 'Delta'),
        ('Warri South', 'warri-south', '24', 'Delta'),
        ('Warri South West', 'warri-south-west', '25', 'Delta'),
        ('Abakaliki', 'abakaliki', '01', 'Ebonyi'),
        ('Afikpo North', 'afikpo-north', '02', 'Ebonyi'),
        ('Afikpo South', 'afikpo-south', '03', 'Ebonyi'),
        ('Ebonyi', 'ebonyi', '04', 'Ebonyi'),
        ('Ezza North', 'ezza-north', '05', 'Ebonyi'),
        ('Ezza South', 'ezza-south', '06', 'Ebonyi'),
        ('Ikwo', 'ikwo', '07', 'Ebonyi'),
        ('Ishielu', 'ishielu', '08', 'Ebonyi'),
        ('Ivo', 'ivo', '09', 'Ebonyi'),
        ('Izzi', 'izzi', '10', 'Ebonyi'),
        ('Ohaozara', 'ohaozara', '11', 'Ebonyi'),
        ('Ohaukwu', 'ohaukwu', '12', 'Ebonyi'),
        ('Onicha', 'onicha', '13', 'Ebonyi'),
        ('Akoko Edo', 'akoko-edo', '01', 'Edo'),
        ('Egor', 'egor', '02', 'Edo'),
        ('Esan Central', 'esan-central', '03', 'Edo'),
        ('Esan North East', 'esan-north-east', '04', 'Edo'),
        ('Esan South East', 'esan-south-east', '05', 'Edo'),
        ('Esan West', 'esan-west', '06', 'Edo'),
        ('Etsako Central', 'etsako-central', '07', 'Edo'),
        ('Etsako East', 'etsako-east', '08', 'Edo'),
        ('Etsako West', 'etsako-west', '09', 'Edo'),
        ('Igueben', 'igueben', '10', 'Edo'),
        ('Ikpoba/Okha', 'ikpoba-okha', '11', 'Edo'),
        ('Oredo', 'oredo', '12', 'Edo'),
        ('Orhionmwon', 'orhionmwon', '13', 'Edo'),
        ('Ovia North East', 'ovia-north-east', '14', 'Edo'),
        ('Ovia South West', 'ovia-south-west', '15', 'Edo'),
        ('Owan East', 'owan-east', '16', 'Edo'),
        ('Owan West', 'owan-west', '17', 'Edo'),
        ('Uhunmwode', 'uhunmwode', '18', 'Edo'),
        ('Ado Ekiti', 'ado-ekiti', '01', 'Ekiti'),
        ('Efon', 'efon', '02', 'Ekiti'),
        ('Ekiti East', 'ekiti-east', '03', 'Ekiti'),
        ('Ekiti West', 'ekiti-west', '04', 'Ekiti'),
        ('Ekiti South West', 'ekiti-south-west', '05', 'Ekiti'),
        ('Emure', 'emure', '06', 'Ekiti'),
        ('Aiyekire', 'aiyekire', '07', 'Ekiti'),
        ('Ido/Osi', 'ido-osi', '08', 'Ekiti'),
        ('Ijero', 'ijero', '09', 'Ekiti'),
        ('Ikere', 'ikere', '10', 'Ekiti'),
        ('Ikole', 'ikole', '11', 'Ekiti'),
        ('Ilejemeje', 'ilejemeje', '12', 'Ekiti'),
        ('Irepodun/Ifelodun', 'irepodun-ifelodun', '13', 'Ekiti'),
        ('Ise/Orun', 'ise-orun', '14', 'Ekiti'),
        ('Moba', 'moba', '15', 'Ekiti'),
        ('Oye', 'oye', '16', 'Ekiti'),
        ('Aninri', 'aninri', '01', 'Enugu'),
        ('Awgu', 'awgu', '02', 'Enugu'),
        ('Enugu East', 'enugu-east', '03', 'Enugu'),
        ('Enugu North', 'enugu-north', '04', 'Enugu'),
        ('Enugu South', 'enugu-south', '05', 'Enugu'),
        ('Ezeagu', 'ezeagu', '06', 'Enugu'),
        ('Igbo Etiti', 'igbo-etiti', '07', 'Enugu'),
        ('Igbo Eze North', 'igbo-eze-north', '08', 'Enugu'),
        ('Igbo Eze South', 'igbo-eze-south', '09', 'Enugu'),
        ('Isi Uzo', 'isi-uzo', '10', 'Enugu'),
        ('Nkanu East', 'nkanu-east', '11', 'Enugu'),
        ('Nkanu West', 'nkanu-west', '12', 'Enugu'),
        ('Nsukka', 'nsukka', '13', 'Enugu'),
        ('Oji-River', 'oji-river', '14', 'Enugu'),
        ('Udenu', 'udenu', '15', 'Enugu'),
        ('Udi', 'udi', '16', 'Enugu'),
        ('Uzo-Uwani', 'uzo-uwani', '17', 'Enugu'),
        ('Abaji', 'abaji', '01', 'Federal Capital Territory'),
        ('Bwari', 'bwari', '02', 'Federal Capital Territory'),
        ('Gwagwalada', 'gwagwalada', '03', 'Federal Capital Territory'),
        ('Kuje', 'kuje', '04', 'Federal Capital Territory'),
        ('Kwali', 'kwali', '05', 'Federal Capital Territory'),
        ('Municipal', 'municipal', '06', 'Federal Capital Territory'),
        ('Akko', 'akko', '01', 'Gombe'),
        ('Balanga', 'balanga', '02', 'Gombe'),
        ('Billiri', 'billiri', '03', 'Gombe'),
        ('Dukku', 'dukku', '04', 'Gombe'),
        ('Funakaye', 'funakaye', '05', 'Gombe'),
        ('Gombe', 'gombe', '06', 'Gombe'),
        ('Kaltungo', 'kaltungo', '07', 'Gombe'),
        ('Kwami', 'kwami', '08', 'Gombe'),
        ('Nafada', 'nafada', '09', 'Gombe'),
        ('Shongom', 'shongom', '10', 'Gombe'),
        ('Yalmaltu/Deba', 'yalmaltu-deba', '11', 'Gombe'),
        ('Aboh Mbaise', 'aboh-mbaise', '01', 'Imo'),
        ('Ahiazu Mbaise', 'ahiazu-mbaise', '02', 'Imo'),
        ('Ehime Mbano', 'ehime-mbano', '03', 'Imo'),
        ('Ezinihitte Mbaise', 'ezinihitte-mbaise', '04', 'Imo'),
        ('Ideato North', 'ideato-north', '05', 'Imo'),
        ('Ideato South', 'ideato-south', '06', 'Imo'),
        ('Ihitte Uboma', 'ihitte-uboma', '07', 'Imo'),
        ('Ikeduru', 'ikeduru', '08', 'Imo'),
        ('Isiala Mbano', 'isiala-mbano', '09', 'Imo'),
        ('Isu', 'isu', '10', 'Imo'),
        ('Mbaitoli', 'mbaitoli', '11', 'Imo'),
        ('Ngor Okpala', 'ngor-okpala', '12', 'Imo'),
        ('Njaba', 'njaba', '13', 'Imo'),
        ('Nkwerre', 'nkwerre', '14', 'Imo'),
        ('Nwangele', 'nwangele', '15', 'Imo'),
        ('Obowo', 'obowo', '16', 'Imo'),
        ('Oguta', 'oguta', '17', 'Imo'),
        ('Ohaji Egbema', 'ohaji-egbema', '18', 'Imo'),
        ('Okigwe', 'okigwe', '19', 'Imo'),
        ('Onuimo', 'onuimo', '20', 'Imo'),
        ('Orlu', 'orlu', '21', 'Imo'),
        ('Orsu', 'orsu', '22', 'Imo'),
        ('Oru East', 'oru-east', '23', 'Imo'),
        ('Oru West', 'oru-west', '24', 'Imo'),
        ('Owerri Municipal', 'owerri-municipal', '25', 'Imo'),
        ('Owerri North', 'owerri-north', '26', 'Imo'),
        ('Owerri West', 'owerri-west', '27', 'Imo'),
        ('Auyo', 'auyo', '01', 'Jigawa'),
        ('Babura', 'babura', '02', 'Jigawa'),
        ('Birnin Kudu', 'birnin-kudu', '03', 'Jigawa'),
        ('Birniwa', 'birniwa', '04', 'Jigawa'),
        ('Buji', 'buji', '05', 'Jigawa'),
        ('Dutse', 'dutse', '06', 'Jigawa'),
        ('Garki', 'garki', '07', 'Jigawa'),
        ('Gagarawa', 'gagarawa', '08', 'Jigawa'),
        ('Gumel', 'gumel', '09', 'Jigawa'),
        ('Guri', 'guri', '10', 'Jigawa'),
        ('Gwaram', 'gwaram', '11', 'Jigawa'),
        ('Gwiwa', 'gwiwa', '12', 'Jigawa'),
        ('Hadejia', 'hadejia', '13', 'Jigawa'),
        ('Jahun', 'jahun', '14', 'Jigawa'),
        ('Kafin Hausa', 'kafin-hausa', '15', 'Jigawa'),
        ('Kaugama', 'kaugama', '16', 'Jigawa'),
        ('Kazaure', 'kazaure', '17', 'Jigawa'),
        ('Kirika Samma', 'kirika-samma', '18', 'Jigawa'),
        ('Kiyawa', 'kiyawa', '19', 'Jigawa'),
        ('Maigatari', 'maigatari', '20', 'Jigawa'),
        ('Malam Madori', 'malam-madori', '21', 'Jigawa'),
        ('Miga', 'miga', '22', 'Jigawa'),
        ('Ringim', 'ringim', '23', 'Jigawa'),
        ('Roni', 'roni', '24', 'Jigawa'),
        ('Sule-Tankarkar', 'sule-tankarkar', '25', 'Jigawa'),
        ('Taura', 'taura', '26', 'Jigawa'),
        ('Yankwashi', 'yankwashi', '27', 'Jigawa'),
        ('Birnin Gwari', 'birnin-gwari', '01', 'Kaduna'),
        ('Chikun', 'chikun', '02', 'Kaduna'),
        ('Giwa', 'giwa', '03', 'Kaduna'),
        ('Igabi', 'igabi', '04', 'Kaduna'),
        ('Ikara', 'ikara', '05', 'Kaduna'),
        ('Jaba', 'jaba', '06', 'Kaduna'),
        ('Jema''a', 'jemaa', '07', 'Kaduna'),
        ('Kachia', 'kachia', '08', 'Kaduna'),
        ('Kaduna North', 'kaduna-north', '09', 'Kaduna'),
        ('Kaduna South', 'kaduna-south', '10', 'Kaduna'),
        ('Kagarko', 'kagarko', '11', 'Kaduna'),
        ('Kajuru', 'kajuru', '12', 'Kaduna'),
        ('Kaura', 'kaura', '13', 'Kaduna'),
        ('Kauru', 'kauru', '14', 'Kaduna'),
        ('Kubau', 'kubau', '15', 'Kaduna'),
        ('Kudan', 'kudan', '16', 'Kaduna'),
        ('Lere', 'lere', '17', 'Kaduna'),
        ('Makarfi', 'makarfi', '18', 'Kaduna'),
        ('Sabon Gari', 'sabon-gari', '19', 'Kaduna'),
        ('Sanga', 'sanga', '20', 'Kaduna'),
        ('Soba', 'soba', '21', 'Kaduna'),
        ('Zangon Kataf', 'zangon-kataf', '22', 'Kaduna'),
        ('Zaria', 'zaria', '23', 'Kaduna'),
        ('Ajingi', 'ajingi', '01', 'Kano'),
        ('Albasu', 'albasu', '02', 'Kano'),
        ('Bagwai', 'bagwai', '03', 'Kano'),
        ('Bebeji', 'bebeji', '04', 'Kano'),
        ('Bichi', 'bichi', '05', 'Kano'),
        ('Bunkure', 'bunkure', '06', 'Kano'),
        ('Dala', 'dala', '07', 'Kano'),
        ('Danbata', 'danbata', '08', 'Kano'),
        ('Dawaki Kudu', 'dawaki-kudu', '09', 'Kano'),
        ('Dawaki Tofa', 'dawaki-tofa', '10', 'Kano'),
        ('Doguwa', 'doguwa', '11', 'Kano'),
        ('Fagge', 'fagge', '12', 'Kano'),
        ('Gabasawa', 'gabasawa', '13', 'Kano'),
        ('Garko', 'garko', '14', 'Kano'),
        ('Garun Malam', 'garun-malam', '15', 'Kano'),
        ('Gaya', 'gaya', '16', 'Kano'),
        ('Gezawa', 'gezawa', '17', 'Kano'),
        ('Gwale', 'gwale', '18', 'Kano'),
        ('Gwarzo', 'gwarzo', '19', 'Kano'),
        ('Kabo', 'kabo', '20', 'Kano'),
        ('Kano Municipal', 'kano-municipal', '21', 'Kano'),
        ('Karaye', 'karaye', '22', 'Kano'),
        ('Kibiya', 'kibiya', '23', 'Kano'),
        ('Kiru', 'kiru', '24', 'Kano'),
        ('Kumbotso', 'kumbotso', '25', 'Kano'),
        ('Kunchi', 'kunchi', '26', 'Kano'),
        ('Kura', 'kura', '27', 'Kano'),
        ('Madobi', 'madobi', '28', 'Kano'),
        ('Makoda', 'makoda', '29', 'Kano'),
        ('Minjibir', 'minjibir', '30', 'Kano'),
        ('Nasarawa', 'nasarawa', '31', 'Kano'),
        ('Rano', 'rano', '32', 'Kano'),
        ('Rimin Gado', 'rimin-gado', '33', 'Kano'),
        ('Rogo', 'rogo', '34', 'Kano'),
        ('Shanono', 'shanono', '35', 'Kano'),
        ('Sumaila', 'sumaila', '36', 'Kano'),
        ('Takai', 'takai', '37', 'Kano'),
        ('Tarauni', 'tarauni', '38', 'Kano'),
        ('Tofa', 'tofa', '39', 'Kano'),
        ('Tsanyawa', 'tsanyawa', '40', 'Kano'),
        ('Tudun Wada', 'tudun-wada', '41', 'Kano'),
        ('Ungogo', 'ungogo', '42', 'Kano'),
        ('Warawa', 'warawa', '43', 'Kano'),
        ('Wudil', 'wudil', '44', 'Kano'),
        ('Bakori', 'bakori', '01', 'Katsina'),
        ('Batagarawa', 'batagarawa', '02', 'Katsina'),
        ('Batsari', 'batsari', '03', 'Katsina'),
        ('Baure', 'baure', '04', 'Katsina'),
        ('Bindawa', 'bindawa', '05', 'Katsina'),
        ('Charanchi', 'charanchi', '06', 'Katsina'),
        ('Dandume', 'dandume', '07', 'Katsina'),
        ('Danja', 'danja', '08', 'Katsina'),
        ('Dan Musa', 'dan-musa', '09', 'Katsina'),
        ('Daura', 'daura', '10', 'Katsina'),
        ('Dutsi', 'dutsi', '11', 'Katsina'),
        ('Dutsin-Ma', 'dutsin-ma', '12', 'Katsina'),
        ('Faskari', 'faskari', '13', 'Katsina'),
        ('Funtua', 'funtua', '14', 'Katsina'),
        ('Ingawa', 'ingawa', '15', 'Katsina'),
        ('Jibia', 'jibia', '16', 'Katsina'),
        ('Kafur', 'kafur', '17', 'Katsina'),
        ('Kaita', 'kaita', '18', 'Katsina'),
        ('Kankara', 'kankara', '19', 'Katsina'),
        ('Kankia', 'kankia', '20', 'Katsina'),
        ('Katsina', 'katsina', '21', 'Katsina'),
        ('Kurfi', 'kurfi', '22', 'Katsina'),
        ('Kusada', 'kusada', '23', 'Katsina'),
        ('Mai''adua', 'maiadua', '24', 'Katsina'),
        ('Malufashi', 'malufashi', '25', 'Katsina'),
        ('Mani', 'mani', '26', 'Katsina'),
        ('Mashi', 'mashi', '27', 'Katsina'),
        ('Matazu', 'matazu', '28', 'Katsina'),
        ('Musawa', 'musawa', '29', 'Katsina'),
        ('Rimi', 'rimi', '30', 'Katsina'),
        ('Sabuwa', 'sabuwa', '31', 'Katsina'),
        ('Safana', 'safana', '32', 'Katsina'),
        ('Sandamu', 'sandamu', '33', 'Katsina'),
        ('Zango', 'zango', '34', 'Katsina'),
        ('Aliero', 'aliero', '01', 'Kebbi'),
        ('Arewa', 'arewa', '02', 'Kebbi'),
        ('Argungu', 'argungu', '03', 'Kebbi'),
        ('Augie', 'augie', '04', 'Kebbi'),
        ('Bagudo', 'bagudo', '05', 'Kebbi'),
        ('Birnin Kebbi', 'birnin-kebbi', '06', 'Kebbi'),
        ('Bunza', 'bunza', '07', 'Kebbi'),
        ('Dandi', 'dandi', '08', 'Kebbi'),
        ('Fakai', 'fakai', '09', 'Kebbi'),
        ('Gwandu', 'gwandu', '10', 'Kebbi'),
        ('Jega', 'jega', '11', 'Kebbi'),
        ('Kalgo', 'kalgo', '12', 'Kebbi'),
        ('Koko/Besse', 'koko-besse', '13', 'Kebbi'),
        ('Maiyama', 'maiyama', '14', 'Kebbi'),
        ('Ngaski', 'ngaski', '15', 'Kebbi'),
        ('Sakaba', 'sakaba', '16', 'Kebbi'),
        ('Shanga', 'shanga', '17', 'Kebbi'),
        ('Suru', 'suru', '18', 'Kebbi'),
        ('Wasagu/Danko', 'wasagu-danko', '19', 'Kebbi'),
        ('Yauri', 'yauri', '20', 'Kebbi'),
        ('Zuru', 'zuru', '21', 'Kebbi'),
        ('Adavi', 'adavi', '01', 'Kogi'),
        ('Ajaokuta', 'ajaokuta', '02', 'Kogi'),
        ('Ankpa', 'ankpa', '03', 'Kogi'),
        ('Bassa', 'bassa', '04', 'Kogi'),
        ('Dekina', 'dekina', '05', 'Kogi'),
        ('Ibaji', 'ibaji', '06', 'Kogi'),
        ('Idah', 'idah', '07', 'Kogi'),
        ('Igalamela/Odolu', 'igalamela-odolu', '08', 'Kogi'),
        ('Ijumu', 'ijumu', '09', 'Kogi'),
        ('Kabba/Bunu', 'kabba-bunu', '10', 'Kogi'),
        ('Kogi/Kotonkarfe', 'kogi-kotonkarfe', '11', 'Kogi'),
        ('Lokoja', 'lokoja', '12', 'Kogi'),
        ('Mopa Moro', 'mopa-moro', '13', 'Kogi'),
        ('Ofu', 'ofu', '14', 'Kogi'),
        ('Ogori Mangogo', 'ogori-mangogo', '15', 'Kogi'),
        ('Okehi', 'okehi', '16', 'Kogi'),
        ('Okene', 'okene', '17', 'Kogi'),
        ('Olamaboro', 'olamaboro', '18', 'Kogi'),
        ('Omala', 'omala', '19', 'Kogi'),
        ('Yagba East', 'yagba-east', '20', 'Kogi'),
        ('Yagba West', 'yagba-west', '21', 'Kogi'),
        ('Asa', 'asa', '01', 'Kwara'),
        ('Baruten', 'baruten', '02', 'Kwara'),
        ('Edu', 'edu', '03', 'Kwara'),
        ('Ekiti', 'ekiti', '04', 'Kwara'),
        ('Ifelodun', 'ifelodun', '05', 'Kwara'),
        ('Ilorin East', 'ilorin-east', '06', 'Kwara'),
        ('Ilorin-South', 'ilorin-south', '07', 'Kwara'),
        ('Ilorin-West', 'ilorin-west', '08', 'Kwara'),
        ('Irepodun', 'irepodun', '09', 'Kwara'),
        ('Isin', 'isin', '10', 'Kwara'),
        ('Kaiama', 'kaiama', '11', 'Kwara'),
        ('Moro', 'moro', '12', 'Kwara'),
        ('Offa', 'offa', '13', 'Kwara'),
        ('Oke-Ero', 'oke-ero', '14', 'Kwara'),
        ('Oyun', 'oyun', '15', 'Kwara'),
        ('Patigi', 'patigi', '16', 'Kwara'),
        ('Agege', 'agege', '01', 'Lagos'),
        ('Ajeromi/Ifelodun', 'ajeromi-ifelodun', '02', 'Lagos'),
        ('Alimosho', 'alimosho', '03', 'Lagos'),
        ('Amuwo-Odofin', 'amuwo-odofin', '04', 'Lagos'),
        ('Apapa', 'apapa', '05', 'Lagos'),
        ('Badagry', 'badagry', '06', 'Lagos'),
        ('Epe', 'epe', '07', 'Lagos'),
        ('Eti-Osa', 'eti-osa', '08', 'Lagos'),
        ('Ibeju/Lekki', 'ibeju-lekki', '09', 'Lagos'),
        ('Ifako-Ijaye', 'ifako-ijaye', '10', 'Lagos'),
        ('Ikeja', 'ikeja', '11', 'Lagos'),
        ('Ikorodu', 'ikorodu', '12', 'Lagos'),
        ('Kosofe', 'kosofe', '13', 'Lagos'),
        ('Lagos Island', 'lagos-island', '14', 'Lagos'),
        ('Lagos Mainland', 'lagos-mainland', '15', 'Lagos'),
        ('Mushin', 'mushin', '16', 'Lagos'),
        ('Ojo', 'ojo', '17', 'Lagos'),
        ('Oshodi/Isolo', 'oshodi-isolo', '18', 'Lagos'),
        ('Somolu', 'somolu', '19', 'Lagos'),
        ('Surulere', 'surulere', '20', 'Lagos'),
        ('Akwanga', 'akwanga', '01', 'Nasarawa'),
        ('Awe', 'awe', '02', 'Nasarawa'),
        ('Doma', 'doma', '03', 'Nasarawa'),
        ('Karu', 'karu', '04', 'Nasarawa'),
        ('Keana', 'keana', '05', 'Nasarawa'),
        ('Keffi', 'keffi', '06', 'Nasarawa'),
        ('Kokona', 'kokona', '07', 'Nasarawa'),
        ('Lafia', 'lafia', '08', 'Nasarawa'),
        ('Nasarawa Eggon', 'nasarawa-eggon', '10', 'Nasarawa'),
        ('Toto', 'toto', '12', 'Nasarawa'),
        ('Wamba', 'wamba', '13', 'Nasarawa'),
        ('Nasarawa', 'nasarawa', '09', 'Nasarawa'),
        ('Obi', 'obi', '11', 'Nasarawa'),
        ('Agaie', 'agaie', '01', 'Niger'),
        ('Agwara', 'agwara', '02', 'Niger'),
        ('Bida', 'bida', '03', 'Niger'),
        ('Borgu', 'borgu', '04', 'Niger'),
        ('Bosso', 'bosso', '05', 'Niger'),
        ('Chanchaga', 'chanchaga', '06', 'Niger'),
        ('Edatti', 'edatti', '07', 'Niger'),
        ('Gbako', 'gbako', '08', 'Niger'),
        ('Gurara', 'gurara', '09', 'Niger'),
        ('Katcha', 'katcha', '10', 'Niger'),
        ('Kontagora', 'kontagora', '11', 'Niger'),
        ('Lapai', 'lapai', '12', 'Niger'),
        ('Lavun', 'lavun', '13', 'Niger'),
        ('Magama', 'magama', '14', 'Niger'),
        ('Mariga', 'mariga', '15', 'Niger'),
        ('Mashegu', 'mashegu', '16', 'Niger'),
        ('Mokwa', 'mokwa', '17', 'Niger'),
        ('Munya', 'munya', '18', 'Niger'),
        ('Paikoro', 'paikoro', '19', 'Niger'),
        ('Rafi', 'rafi', '20', 'Niger'),
        ('Rijau', 'rijau', '21', 'Niger'),
        ('Shiroro', 'shiroro', '22', 'Niger'),
        ('Suleja', 'suleja', '23', 'Niger'),
        ('Tafa', 'tafa', '24', 'Niger'),
        ('Wushishi', 'wushishi', '25', 'Niger'),
        ('Abeokuta North', 'abeokuta-north', '01', 'Ogun'),
        ('Abeokuta South', 'abeokuta-south', '02', 'Ogun'),
        ('Ado Odo-Ota', 'ado-odo-ota', '03', 'Ogun'),
        ('Egbado North', 'egbado-north', '04', 'Ogun'),
        ('Egbado South', 'egbado-south', '05', 'Ogun'),
        ('Ewekoro', 'ewekoro', '06', 'Ogun'),
        ('Ifo', 'ifo', '07', 'Ogun'),
        ('Ijebu East', 'ijebu-east', '08', 'Ogun'),
        ('Ijebu North', 'ijebu-north', '09', 'Ogun'),
        ('Ijebu North East', 'ijebu-north-east', '10', 'Ogun'),
        ('Ijebu Ode', 'ijebu-ode', '11', 'Ogun'),
        ('Ikenne', 'ikenne', '12', 'Ogun'),
        ('Imeko/Afon', 'imeko-afon', '13', 'Ogun'),
        ('Ipokia', 'ipokia', '14', 'Ogun'),
        ('Obafemi/Owode', 'obafemi-owode', '15', 'Ogun'),
        ('Odeda', 'odeda', '16', 'Ogun'),
        ('Odogbolu', 'odogbolu', '17', 'Ogun'),
        ('Ogun Water Side', 'ogun-water-side', '18', 'Ogun'),
        ('Remo North', 'remo-north', '19', 'Ogun'),
        ('Sagamu', 'sagamu', '20', 'Ogun'),
        ('Akoko North East', 'akoko-north-east', '01', 'Ondo'),
        ('Akoko North West', 'akoko-north-west', '02', 'Ondo'),
        ('Akoko South East', 'akoko-south-east', '03', 'Ondo'),
        ('Akoko South West', 'akoko-south-west', '04', 'Ondo'),
        ('Akure North', 'akure-north', '05', 'Ondo'),
        ('Akure South', 'akure-south', '06', 'Ondo'),
        ('Ese-Odo', 'ese-odo', '07', 'Ondo'),
        ('Idanre', 'idanre', '08', 'Ondo'),
        ('Ifedore', 'ifedore', '09', 'Ondo'),
        ('Ilaje', 'ilaje', '10', 'Ondo'),
        ('Ileoluji/Okeigbo', 'ileoluji-okeigbo', '11', 'Ondo'),
        ('Irele', 'irele', '12', 'Ondo'),
        ('Odigbo', 'odigbo', '13', 'Ondo'),
        ('Okitipupa', 'okitipupa', '14', 'Ondo'),
        ('Ondo East', 'ondo-east', '15', 'Ondo'),
        ('Ondo West', 'ondo-west', '16', 'Ondo'),
        ('Ose', 'ose', '17', 'Ondo'),
        ('Owo', 'owo', '18', 'Ondo'),
        ('Atakumosa East', 'atakumosa-east', '01', 'Osun'),
        ('Atakumosa West', 'atakumosa-west', '02', 'Osun'),
        ('Ayedaade', 'ayedaade', '03', 'Osun'),
        ('Ayedire', 'ayedire', '04', 'Osun'),
        ('Boluwaduro', 'boluwaduro', '05', 'Osun'),
        ('Boripe', 'boripe', '06', 'Osun'),
        ('Ede North', 'ede-north', '07', 'Osun'),
        ('Ede South', 'ede-south', '08', 'Osun'),
        ('Egbedore', 'egbedore', '09', 'Osun'),
        ('Ejigbo', 'ejigbo', '10', 'Osun'),
        ('Ife Central', 'ife-central', '11', 'Osun'),
        ('Ifedayo', 'ifedayo', '12', 'Osun'),
        ('Ife East', 'ife-east', '13', 'Osun'),
        ('Ife North', 'ife-north', '15', 'Osun'),
        ('Ife South', 'ife-south', '16', 'Osun'),
        ('Ila', 'ila', '17', 'Osun'),
        ('Ilesa East', 'ilesa-east', '18', 'Osun'),
        ('Ilesa West', 'ilesa-west', '19', 'Osun'),
        ('Irewole', 'irewole', '21', 'Osun'),
        ('Isokan', 'isokan', '22', 'Osun'),
        ('Iwo', 'iwo', '23', 'Osun'),
        ('Obokun', 'obokun', '24', 'Osun'),
        ('Odo-Otin', 'odo-otin', '25', 'Osun'),
        ('Ola-Oluwa', 'ola-oluwa', '26', 'Osun'),
        ('Olorunda', 'olorunda', '27', 'Osun'),
        ('Oriade', 'oriade', '28', 'Osun'),
        ('Orolu', 'orolu', '29', 'Osun'),
        ('Osogbo', 'osogbo', '30', 'Osun'),
        ('Irepodun', 'irepodun', '20', 'Osun'),
        ('Ifelodun', 'ifelodun', '14', 'Osun'),
        ('Afijio', 'afijio', '01', 'Oyo'),
        ('Akinyele', 'akinyele', '02', 'Oyo'),
        ('Atiba', 'atiba', '03', 'Oyo'),
        ('Atisbo', 'atisbo', '04', 'Oyo'),
        ('Egbeda', 'egbeda', '05', 'Oyo'),
        ('Ibadan North', 'ibadan-north', '06', 'Oyo'),
        ('Ibadan North East', 'ibadan-north-east', '07', 'Oyo'),
        ('Ibadan North West', 'ibadan-north-west', '08', 'Oyo'),
        ('Ibadan South-East', 'ibadan-south-east', '09', 'Oyo'),
        ('Ibadan South West', 'ibadan-south-west', '10', 'Oyo'),
        ('Ibarapa Central', 'ibarapa-central', '11', 'Oyo'),
        ('Ibarapa East', 'ibarapa-east', '12', 'Oyo'),
        ('Ibarapa North', 'ibarapa-north', '13', 'Oyo'),
        ('Ido', 'ido', '14', 'Oyo'),
        ('Irepo', 'irepo', '15', 'Oyo'),
        ('Iseyin', 'iseyin', '16', 'Oyo'),
        ('Itesiwaju', 'itesiwaju', '17', 'Oyo'),
        ('Iwajowa', 'iwajowa', '18', 'Oyo'),
        ('Kajola', 'kajola', '19', 'Oyo'),
        ('Lagelu', 'lagelu', '20', 'Oyo'),
        ('Ogbomoso North', 'ogbomoso-north', '21', 'Oyo'),
        ('Ogbomoso South', 'ogbomoso-south', '22', 'Oyo'),
        ('Ogo-Oluwa', 'ogo-oluwa', '23', 'Oyo'),
        ('Olorunsogo', 'olorunsogo', '24', 'Oyo'),
        ('Oluyole', 'oluyole', '25', 'Oyo'),
        ('Ona-Ara', 'ona-ara', '26', 'Oyo'),
        ('Oorelope', 'oorelope', '27', 'Oyo'),
        ('Ori Ire', 'ori-ire', '28', 'Oyo'),
        ('Oyo East', 'oyo-east', '29', 'Oyo'),
        ('Oyo West', 'oyo-west', '30', 'Oyo'),
        ('Saki East', 'saki-east', '31', 'Oyo'),
        ('Saki West', 'saki-west', '32', 'Oyo'),
        ('Surulere', 'surulere', '33', 'Oyo'),
        ('Barikin Ladi', 'barikin-ladi', '01', 'Plateau'),
        ('Bokkos', 'bokkos', '03', 'Plateau'),
        ('Jos East', 'jos-east', '04', 'Plateau'),
        ('Jos North', 'jos-north', '05', 'Plateau'),
        ('Jos South', 'jos-south', '06', 'Plateau'),
        ('Kanam', 'kanam', '07', 'Plateau'),
        ('Kanke', 'kanke', '08', 'Plateau'),
        ('Langtang North', 'langtang-north', '09', 'Plateau'),
        ('Langtang South', 'langtang-south', '10', 'Plateau'),
        ('Mangu', 'mangu', '11', 'Plateau'),
        ('Mikang', 'mikang', '12', 'Plateau'),
        ('Pankshin', 'pankshin', '13', 'Plateau'),
        ('Qua''an Pan', 'quaan-pan', '14', 'Plateau'),
        ('Riyom', 'riyom', '15', 'Plateau'),
        ('Shendam', 'shendam', '16', 'Plateau'),
        ('Wase', 'wase', '17', 'Plateau'),
        ('Bassa', 'bassa', '02', 'Plateau'),
        ('Abua-Odual', 'abua-odual', '01', 'Rivers'),
        ('Ahoada East', 'ahoada-east', '02', 'Rivers'),
        ('Ahoada West', 'ahoada-west', '03', 'Rivers'),
        ('Akuku Toru', 'akuku-toru', '04', 'Rivers'),
        ('Andoni', 'andoni', '05', 'Rivers'),
        ('Asari-Toru', 'asari-toru', '06', 'Rivers'),
        ('Bonny', 'bonny', '07', 'Rivers'),
        ('Degema', 'degema', '08', 'Rivers'),
        ('Eleme', 'eleme', '09', 'Rivers'),
        ('Emohua', 'emohua', '10', 'Rivers'),
        ('Etche', 'etche', '11', 'Rivers'),
        ('Gokana', 'gokana', '12', 'Rivers'),
        ('Ikwerre', 'ikwerre', '13', 'Rivers'),
        ('Khana', 'khana', '14', 'Rivers'),
        ('Obio/Akpor', 'obio-akpor', '15', 'Rivers'),
        ('Ogba/Egbema/Ndoni', 'ogba-egbema-ndoni', '16', 'Rivers'),
        ('Ogu/Bolo', 'ogu-bolo', '17', 'Rivers'),
        ('Okrika', 'okrika', '18', 'Rivers'),
        ('Omuma', 'omuma', '19', 'Rivers'),
        ('Opobo/Nkoro', 'opobo-nkoro', '20', 'Rivers'),
        ('Oyigbo', 'oyigbo', '21', 'Rivers'),
        ('Port Harcourt', 'port-harcourt', '22', 'Rivers'),
        ('Tai', 'tai', '23', 'Rivers'),
        ('Binji', 'binji', '01', 'Sokoto'),
        ('Bodinga', 'bodinga', '02', 'Sokoto'),
        ('Dange/Shuni', 'dange-shuni', '03', 'Sokoto'),
        ('Gada', 'gada', '04', 'Sokoto'),
        ('Goronyo', 'goronyo', '05', 'Sokoto'),
        ('Gudu', 'gudu', '06', 'Sokoto'),
        ('Gwadabawa', 'gwadabawa', '07', 'Sokoto'),
        ('Illela', 'illela', '08', 'Sokoto'),
        ('Isa', 'isa', '09', 'Sokoto'),
        ('Kware', 'kware', '10', 'Sokoto'),
        ('Kebbe', 'kebbe', '11', 'Sokoto'),
        ('Rabah', 'rabah', '12', 'Sokoto'),
        ('S/Birni', 's-birni', '13', 'Sokoto'),
        ('Shagari', 'shagari', '14', 'Sokoto'),
        ('Silame', 'silame', '15', 'Sokoto'),
        ('Sokoto North', 'sokoto-north', '16', 'Sokoto'),
        ('Sokoto South', 'sokoto-south', '17', 'Sokoto'),
        ('Tambuwal', 'tambuwal', '18', 'Sokoto'),
        ('Tangaza', 'tangaza', '19', 'Sokoto'),
        ('Tureta', 'tureta', '20', 'Sokoto'),
        ('Wamakko', 'wamakko', '21', 'Sokoto'),
        ('Wurno', 'wurno', '22', 'Sokoto'),
        ('Yabo', 'yabo', '23', 'Sokoto'),
        ('Ardo-Kola', 'ardo-kola', '01', 'Taraba'),
        ('Bali', 'bali', '02', 'Taraba'),
        ('Donga', 'donga', '03', 'Taraba'),
        ('Gashaka', 'gashaka', '04', 'Taraba'),
        ('Gassol', 'gassol', '05', 'Taraba'),
        ('Ibi', 'ibi', '06', 'Taraba'),
        ('Jalingo', 'jalingo', '07', 'Taraba'),
        ('Karim-Lamido', 'karim-lamido', '08', 'Taraba'),
        ('Kurmi', 'kurmi', '09', 'Taraba'),
        ('Lau', 'lau', '10', 'Taraba'),
        ('Sardauna', 'sardauna', '11', 'Taraba'),
        ('Takum', 'takum', '12', 'Taraba'),
        ('Ussa', 'ussa', '13', 'Taraba'),
        ('Wukari', 'wukari', '14', 'Taraba'),
        ('Yorro', 'yorro', '15', 'Taraba'),
        ('Zing', 'zing', '16', 'Taraba'),
        ('Bade', 'bade', '01', 'Yobe'),
        ('Bursari', 'bursari', '02', 'Yobe'),
        ('Damaturu', 'damaturu', '03', 'Yobe'),
        ('Fika', 'fika', '04', 'Yobe'),
        ('Fune', 'fune', '05', 'Yobe'),
        ('Geidam', 'geidam', '06', 'Yobe'),
        ('Gujba', 'gujba', '07', 'Yobe'),
        ('Gulani', 'gulani', '08', 'Yobe'),
        ('Jakusko', 'jakusko', '09', 'Yobe'),
        ('Karasawa', 'karasawa', '10', 'Yobe'),
        ('Machina', 'machina', '11', 'Yobe'),
        ('Nangere', 'nangere', '12', 'Yobe'),
        ('Nguru', 'nguru', '13', 'Yobe'),
        ('Potiskum', 'potiskum', '14', 'Yobe'),
        ('Tarmuwa', 'tarmuwa', '15', 'Yobe'),
        ('Yunusari', 'yunusari', '16', 'Yobe'),
        ('Yusufari', 'yusufari', '17', 'Yobe'),
        ('Anka', 'anka', '01', 'Zamfara'),
        ('Bakura', 'bakura', '02', 'Zamfara'),
        ('Birnin Magaji', 'birnin-magaji', '03', 'Zamfara'),
        ('Bukkuyum', 'bukkuyum', '04', 'Zamfara'),
        ('Bungudu', 'bungudu', '05', 'Zamfara'),
        ('Gummi', 'gummi', '06', 'Zamfara'),
        ('Gusau', 'gusau', '07', 'Zamfara'),
        ('Kaura Namoda', 'kaura-namoda', '08', 'Zamfara'),
        ('Maradun', 'maradun', '09', 'Zamfara'),
        ('Maru', 'maru', '10', 'Zamfara'),
        ('Shinkafi', 'shinkafi', '11', 'Zamfara'),
        ('Talata Mafara', 'talata-mafara', '12', 'Zamfara'),
        ('Tsafe', 'tsafe', '13', 'Zamfara'),
        ('Zurmi', 'zurmi', '14', 'Zamfara')
      ) AS v(name, slug, inec_code, state_name)
      JOIN "states" s ON s.name = v.state_name
      ON CONFLICT ("stateId", "name") DO NOTHING
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "lgas" DROP CONSTRAINT "FK_lgas_stateId"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_lgas_stateId"`);
    await queryRunner.query(`DROP TABLE "lgas"`);
    await queryRunner.query(`DROP TABLE "states"`);
  }
}